version: "3.9"

services:
  frontend-chanquinafm:
    image: node:18-alpine
    container_name: frontend-chanquinafm
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build && npm run start"
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_DISABLE_ACTIONS_HOST_VALIDATION: 'true'
    ports:
      - "3000:3000"
    restart: always
